permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: 哈格咂丶的博客
title: 哈格咂丶的博客
description: "哈格咂丶的博客"
keywords: "github,lixiaohui8636,lixiaohui,李孝辉，李孝辉8636，哈格咂"
url: https://lixiaohui8636.github.io
baseurl: ""
domain_name: ttps://lixiaohui8636.github.io
# google_analytics: UA-52446115-1
repo: http://github.com/lixiaohui8636
disqus_shortname: ""

author:
  name      : 哈格咂丶
  image     : /assets/images/author.jpg
  email     : lixiaohui8636@163.com
  url       : http://lixiaohui.top
  facebook  : http://facebook.com/fernando.dev
  twitter   : http://twitter.com/nandomoreirame
  instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/nandomoreirame
  linkedin  : http://linkedin.com/in/nandomoreirame
  bio       : "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
